sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/sidekiq_3.3.1.gemfile
  - gemfiles/sidekiq_3.x.gemfile
  - gemfiles/sidekiq_4.x.gemfile
  - gemfiles/sidekiq_5.x.gemfile
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

cache: bundler
before_install:
  - gem install bundler -v 1.16.5
  - ruby -e "puts Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.2.2')"
after_success: bundle exec codeclimate-test-reporter
script: bundle exec rake spec
